
name = input("Enter your full name: ")
age = int(input("Enter your age: "))
student_ID = input("Enter your ID: ")
city = input("Which city do u leave in: ")
university =  input("Which university do you study: ")
department = input("Which department do you study: ")
email = input("What is your email: ")
phone = int(input("What is your phone number: "))
fav_language = input("What is your favourite programming language: ")
programming_goal = input("What is your goal in programming: ")

print("="*40)
print("          AKIBA STUDENT PROFILE")
print("="*40)
print("")
print(f"Name:      {name}")
print(f"Student ID:      {student_ID}")
print(f"Age:       {age}")
print(f"City:      {city}")
print(f"University:       {university}")
print(f"Deparetment:       {department}")
print(f"Email:           {email}")
print(f"Phone:        {phone}")
print(f"Favorite Language:   {fav_language}")
print("Programming goal:")
print(f"{programming_goal}")
print("")
print("")
print("="*40)